from importlib import import_module

from controllers.console import api, console_ns

CONSOLE_ROUTE_MODULES = (
    "controllers.console.app.app_import",
    "controllers.console.explore.audio",
    "controllers.console.explore.completion",
    "controllers.console.explore.conversation",
    "controllers.console.explore.message",
    "controllers.console.explore.workflow",
    "controllers.console.files",
    "controllers.console.remote_files",
    "controllers.console.apikey",
    "controllers.console.extension",
    "controllers.console.feature",
    "controllers.console.human_input_form",
    "controllers.console.init_validate",
    "controllers.console.notification",
    "controllers.console.ping",
    "controllers.console.setup",
    "controllers.console.spec",
    "controllers.console.version",
    "controllers.console.agent.composer",
    "controllers.console.agent.roster",
    "controllers.console.app.advanced_prompt_template",
    "controllers.console.app.agent",
    "controllers.console.app.agent_app_access",
    "controllers.console.app.agent_app_feature",
    "controllers.console.app.agent_app_sandbox",
    "controllers.console.app.agent_config_inspector",
    "controllers.console.app.agent_drive_inspector",
    "controllers.console.app.annotation",
    "controllers.console.app.app",
    "controllers.console.app.audio",
    "controllers.console.app.completion",
    "controllers.console.app.conversation",
    "controllers.console.app.conversation_variables",
    "controllers.console.app.generator",
    "controllers.console.app.mcp_server",
    "controllers.console.app.message",
    "controllers.console.app.model_config",
    "controllers.console.app.ops_trace",
    "controllers.console.app.site",
    "controllers.console.app.statistic",
    "controllers.console.app.workflow",
    "controllers.console.app.workflow_app_log",
    "controllers.console.app.workflow_comment",
    "controllers.console.app.workflow_draft_variable",
    "controllers.console.app.workflow_node_output_inspector",
    "controllers.console.app.workflow_run",
    "controllers.console.app.workflow_statistic",
    "controllers.console.app.workflow_trigger",
    "controllers.console.auth.activate",
    "controllers.console.auth.data_source_bearer_auth",
    "controllers.console.auth.data_source_oauth",
    "controllers.console.auth.email_register",
    "controllers.console.auth.forgot_password",
    "controllers.console.auth.login",
    "controllers.console.auth.oauth",
    "controllers.console.auth.oauth_server",
    "controllers.console.billing.billing",
    "controllers.console.billing.compliance",
    "controllers.console.datasets.data_source",
    "controllers.console.datasets.datasets",
    "controllers.console.datasets.datasets_document",
    "controllers.console.datasets.datasets_segments",
    "controllers.console.datasets.external",
    "controllers.console.datasets.hit_testing",
    "controllers.console.datasets.metadata",
    "controllers.console.datasets.website",
    "controllers.console.datasets.rag_pipeline.datasource_auth",
    "controllers.console.datasets.rag_pipeline.datasource_content_preview",
    "controllers.console.datasets.rag_pipeline.rag_pipeline",
    "controllers.console.datasets.rag_pipeline.rag_pipeline_datasets",
    "controllers.console.datasets.rag_pipeline.rag_pipeline_draft_variable",
    "controllers.console.datasets.rag_pipeline.rag_pipeline_import",
    "controllers.console.datasets.rag_pipeline.rag_pipeline_workflow",
    "controllers.console.explore.banner",
    "controllers.console.explore.installed_app",
    "controllers.console.explore.parameter",
    "controllers.console.explore.recommended_app",
    "controllers.console.explore.saved_message",
    "controllers.console.explore.trial",
    "controllers.console.snippets.snippet_workflow",
    "controllers.console.snippets.snippet_workflow_draft_variable",
    "controllers.console.socketio.workflow",
    "controllers.console.tag.tags",
    "controllers.console.workspace.account",
    "controllers.console.workspace.agent_providers",
    "controllers.console.workspace.endpoint",
    "controllers.console.workspace.load_balancing_config",
    "controllers.console.workspace.members",
    "controllers.console.workspace.model_providers",
    "controllers.console.workspace.models",
    "controllers.console.workspace.plugin",
    "controllers.console.workspace.rbac",
    "controllers.console.workspace.snippets",
    "controllers.console.workspace.tool_providers",
    "controllers.console.workspace.trigger_providers",
    "controllers.console.workspace.workspace",
)

_routes_loaded = False


def load_console_routes() -> None:
    global _routes_loaded
    if _routes_loaded:
        return

    for module_name in CONSOLE_ROUTE_MODULES:
        import_module(module_name)
    api.add_namespace(console_ns)
    _routes_loaded = True
